# Generated by Django 4.2.23 on 2025-08-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='reminder',
        ),
    ]
